after-login-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Disable macOS feature that hides apps with cmd+h
automatically-unhide-macos-hidden-apps = true

[exec.env-vars]
  PATH = '/etc/profiles/per-user/aleksandernowak/bin:${PATH}'

[key-mapping]
  preset = 'qwerty'

[gaps]
  inner.horizontal = 16
  inner.vertical   = 16
  outer.top        = 32
  outer.left       = 8
  outer.bottom     = 8
  outer.right      = 8

[mode.main.binding]

  alt-slash = 'layout tiles horizontal vertical'
  alt-comma = 'layout accordion horizontal vertical'

  alt-h = 'focus left'
  alt-j = 'focus down'
  alt-k = 'focus up'
  alt-l = 'focus right'

  alt-shift-h = 'move left'
  alt-shift-j = 'move down'
  alt-shift-k = 'move up'
  alt-shift-l = 'move right'

  alt-1 = 'workspace 1' # Chat
  alt-2 = 'workspace 2' # Browser
  alt-3 = 'workspace 3' # Terminal

  alt-shift-1 = 'move-node-to-workspace 1'
  alt-shift-2 = 'move-node-to-workspace 2'
  alt-shift-3 = 'move-node-to-workspace 3'

  alt-tab = 'workspace-back-and-forth'
  alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

  alt-cmd-b = 'exec-and-forget open -na "Firefox" --args --new-window "https://google.com"' # Browser
  alt-cmd-t = 'exec-and-forget open -na "WezTerm"' # Terminal
  alt-cmd-c = 'exec-and-forget open -na "Slack"' # Chat
  alt-cmd-d = 'exec-and-forget open -a "Notion"' # Docs

  alt-f = 'fullscreen'

  alt-shift-semicolon = 'mode service'

[mode.service.binding]
  esc = ['reload-config', 'mode main']
  r = ['flatten-workspace-tree', 'mode main'] # reset layout
  f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
  backspace = ['close-all-windows-but-current', 'mode main']

  alt-shift-h = ['join-with left', 'mode main']
  alt-shift-j = ['join-with down', 'mode main']
  alt-shift-k = ['join-with up', 'mode main']
  alt-shift-l = ['join-with right', 'mode main']
