#!/bin/bash

### TOOLS
brew upgrade
brew install --cask wezterm
brew install \
    nvim \
    ripgrep \
    lazygit \
    tmux \
    wget \
    node \
    fsouza/prettierd/prettierd

mkdir "$HOME/.npm-global"
npm config set prefix "$HOME/.npm-global"

chmod -R +x $PWD/bin

### ZSH
tee -a $HOME/.zshrc << EOF
### AUTO-GENERATED BY $PWD/setup.sh ###
source $PWD/zsh/alias
export PATH="\$PATH:$HOME/.local/bin"
export PATH="\$PATH:$HOME/.npm-global/bin"
export PATH="\$PATH:$HOME/go/bin"
export PATH="\$PATH:$PWD/bin"
export PRETTIERD_DEFAULT_CONFIG="$PWD/.prettierrc.json"
### DO NOT EDIT ###
EOF

### GIT
tee -a $HOME/.gitconfig << EOF
[include]
    path = $PWD/git/alias
EOF

wget -O $HOME/.local/bin/helm_ls https://github.com/mrjosh/helm-ls/releases/download/master/helm_ls_darwin_amd64
chmod +x $HOME/.local/bin/helm_ls

npm i -g \
  vscode-langservers-extracted \
  textlint \
  textlint-rule-write-good \
  textlint-rule-en-spell

go install github.com/katbyte/terrafmt@latest

cp -f ./.textlintrc.json $HOME
