keys:
  - &alek age1ukyl0j56rra50wr55a7lw50504tfhqjentaf793gty5unxxxl9ws3m7r27
  - &machine age1r3r7zk5y3d47gh506fvdsrllznujtd96z52x6t9l6tmccvcd3gvsahp7cw
creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age:
          - *alek
          - *machine
