return {
  "mfussenegger/nvim-dap",
  lazy = true,
  keys = {
    {
      "<leader>db",
      function()
        require("dap").toggle_breakpoint()
      end,
    },
    {
      "<leader>dc",
      function()
        require("dap").continue()
      end,
    },
    {
      "<leader>dC",
      function()
        require("dap").run_to_cursor()
      end,
    },
    {
      "<leader>dT",
      function()
        require("dap").terminate()
      end,
    },
    {
      "<leader>dj",
      function()
        require("dap").step_into()
      end,
    },
    {
      "<leader>dl",
      function()
        require("dap").step_over()
      end,
    },
    {
      "<leader>dh",
      function()
        require("dap").step_back()
      end,
    },
  },
}
