#!/bin/bash

alias tf='terraform'
alias tf119='${HOME}/Downloads/terraform'

alias python='python3'

alias k='kubectl'
alias kcvm='kubectl config view --minify | grep current'
alias kcuc='kubectl config use-context'

alias i='istioctl'

alias tfws='terraform workspace select'

alias k9h='k9s --headless'

alias tffv='terraform fmt --recursive && tf validate'

alias ghpcf='gh pr create --fill'

alias act='DOCKER_HOST=$(docker context inspect --format '{{.Endpoints.docker.Host}}') /opt/homebrew/bin/act'
