#!/bin/bash

alias tf='terraform'
alias tf119='${HOME}/Downloads/terraform'

alias mysql='mysqlsh'

alias python='python3'

alias k='kubectl'
alias kcvm='kubectl config view --minify | grep current'
alias kcuc='kubectl config use-context'

alias i='istioctl'

alias tfws='terraform workspace select'

alias k9h='k9s --headless'
